[package]
name = "openheimer"
version = "2.0.0-alpha"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.2", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.6", features = ["sqlite", "runtime-tokio-rustls"] }
async-trait = "0.1.68"
colored = "2.0.0"
chrono = "0.4.24"
toml = "0.7.3"
