[package]
name = "openheimer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.2"
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.6", features = ["sqlite", "runtime-tokio-rustls"] }
async-trait = "0.1.68"
