name: Build
on:
  push:
    paths:
      - '**.nix'
      - '**.rs'
      - Cargo.*
      - flake.lock
  pull_request:
  workflow_dispatch:

jobs:
  openheimer:
    name: openheimer
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: |
            log-lines = 500

      - name: Set up Cachix
        uses: cachix/cachix-action@v13
        with:
          name: errornobinaries
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build default package
        run: nix build -L
