name: Nix
on:
  push:
    paths:
      - '**.nix'
      - flake.lock
  pull_request:
  workflow_dispatch:

jobs:
  check-flake:
    name: Check flake
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: |
            log-lines = 500

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          fail-mode: true
          check-outdated: false

      - name: Check Nix flake outputs
        run: nix flake check -v --all-systems
