name: Rust
on:
  push:
    paths:
      - '**.rs'
      - Cargo.*
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          extra-conf: |
            log-lines = 500

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Set up build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: build-${{ runner.os }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('flake.nix') }}-${{ hashFiles('**.lock') }}

      - name: Run cargo test
        run: nix develop -c cargo test
